# Project Set up 
# BNE Fast Uncertainty Analysis for ISEE
# Bayesian Nonparametric Ensemble 
# Sebastian T. Rowland 

####***********************
#### Table of Contents ####
####***********************

# 0: Preparation 
# 1: Load Packages for Analysis
# 2: Set Features
# 3: Load Functions 
# 4: Make CONUS Outline

####********************
#### 0: Preparation ####
####********************

# 0a Indicate that the script was run
# although it is intuitive to run this at the end of the script, 
# that creates a recursion with the functions
Ran_a_00 <- "Ran_a_00"

# 0b Load pacman package
library(pacman)

####***********************************
#### 1: Load Packages for Analysis ####
####***********************************

# 1a Load Packages
p_load(tidyverse, lubridate, magrittr, janitor, # tidyverse packages
       sf, raster, rgdal, sp, stars, ncdf4, deldir, dismo,nngeo, ncf, # spatial packages 
       prism, # packages with data 
       tidycensus,
       fst, FNN,
       latex2exp,
       purrr, furrr, future, progress, progressr, # efficiency/paralleization packages
       mgcv, dlnm, splines, lme4, # stats packages
       egg, cowplot, corrplot, pals, colorspace, ggsci, scico) # plotting

# ggsci provides the pallette we use to visualize the folds
#library(devtools)
#install_github('hunzikp/velox')
# nice way to make voronoi's
#if (!require(devtools)) install.packages("devtools")
#devtools::install_github("walshc/voronoi")

####*********************
#### 2: Set Features ####
####*********************

# 2a set the projection string 
#projString <- "epsg:5070"
#projStringRas <- "+init=epsg:5070"
projString <- "epsg:2163"
#projStringRas <- "+init=epsg:2163"

####*************************
#### 3: Source Functions ####
####*************************

# 3a Get the names of all of the scripts that are just functions
# we want both the stable and unstable functions. 
myStableFunctions <- list.files(path = here::here('scripts', '0_functions'))
myUnstableFunctions <- list.files(path = here::here('scripts', '1_unstable_functions'))
myFunctions <- c(myStableFunctions, myUnstableFunctions)

# 3b Define function to run sources 
source_myFunction <- function(Location, FunctionName){
        source(here::here('scripts', Location, FunctionName))
}

# 3c Source all the function scripts
# we don't actually need the assignment, it just removes annoying 
# output generated by the sourcing code. 
# since we are just sourcing these, we can just use map. 
a <- map2(c(rep('0_functions', length(myStableFunctions)), 
            rep('1_unstable_functions', length(myUnstableFunctions))),
                myFunctions, source_myFunction)
            
rm(a, source_myFunction, myFunctions, myStableFunctions, myUnstableFunctions)

####***************************
#### 4: Make CONUS Outline ####
####***************************

# 4a Make the CONUS outline shapefile 
#if it has not already been made
if(!file.exists(here::here('ancillary_data', 'formatted', 'spatial_outlines', 'conus.shp'))){
        source(here::here('scripts', 'a_set_up', 'a_01_make_conusOutline.R'))
}
