# File: a_00_import_packages_set_global_objects.R
# Authors:
# Lawrence Chillrud <lgc2139@cumc.columbia.edu>
# Sebastian Rowland <sr3463@cumc.columbia.edu>
# Date: 01/14/21
#
# Contents:
#  0. Prepare
#  1. Load Packages 
#  2. Set Project-Wide Objects
#  3. Load Functions 
#  4. Make CONUS outline

#### ------------ ####
####  0. PREPARE  ####
#### ------------ ####

# 0.a. indicate that the script was run
# although it is intuitive to run this at the end of the script, 
# that creates a recursion with the functions
ran_a_00 <- "ran_a_00"

# 0.b. load pacman package
library(pacman)

#### ------------------ ####
####  1. LOAD PACKAGES  ####
#### ------------------ ####

# 1.a. load packages
p_load(tidyverse, lubridate, magrittr, janitor, # tidyverse packages
       sf, raster, rgdal, sp, stars, ncdf4, deldir, dismo,nngeo, ncf, # spatial packages 
       prism, # packages with data 
       tidycensus, foreach,
       fst, FNN,
       latex2exp,
       purrr, furrr, future, progress, progressr, # efficiency/parallelezation packages
       mgcv, dlnm, splines, lme4, # stats packages
       egg, cowplot, corrplot, pals, colorspace, ggsci, scico, viridis) # plotting

# ggsci provides the pallette we use to visualize the folds
#library(devtools)
#install_github('hunzikp/velox')
# nice way to make voronoi's
#if (!require(devtools)) install.packages("devtools")
#devtools::install_github("walshc/voronoi")

#### ----------------------------- ####
####  2. SET PROJECT-WIDE OBJECTS  ####
#### ----------------------------- ####

# we create certain objects here to stay in the environment so we can call them 
# for various scripts

# 2a. set the projection string 
# US National Atlas Equal Area
projCRS<- "epsg:2163"
projCRS.ras <- paste0('+init=', projCRS)
plotCRS <- "epsg:4326"

#### --------------------- ####
####  3. SOURCE FUNCTIONS  ####
#### --------------------- ####

# 3.a. get the names of all of the scripts that are just functions
# we want both the stable and unstable functions. 
myStableFunctions <- list.files(path = here::here('scripts', '0_functions'))
myUnstableFunctions <- list.files(path = here::here('scripts', '1_unstable_functions'))
myFunctions <- c(myStableFunctions, myUnstableFunctions)

# 3.b. define function to run sources 
source_myFunction <- function(Location, FunctionName){
        source(here::here('scripts', Location, FunctionName))
}

# 3.c. source all the function scripts
# we don't actually need the assignment, it just removes annoying 
# output generated by the sourcing code. 
# since we are just sourcing these, we can just use map. 
a <- map2(c(rep('0_functions', length(myStableFunctions)), 
            rep('1_unstable_functions', length(myUnstableFunctions))),
                myFunctions, source_myFunction)
        
# 3.d. clean up environment    
rm(a, source_myFunction, myFunctions, myStableFunctions, myUnstableFunctions)

#### ----------------------- ####
####  4. MAKE CONUS OUTLINE  ####
#### ----------------------- ####

# 4.a. make the CONUS outline shapefile 
# if it has not already been made
if(!file.exists(here::here('ancillary_data', 'formatted', 'spatial_outlines', 'conus.shp'))){
        source(here::here('scripts', 'a_set_up', 'a_01_make_conus_outline.R'))
}
