# Project Set up 
# BNE Fast Uncertainty Analysis for ISEE
# Bayesian Nonparametric Ensemble 
# Sebastian T. Rowland 

####***********************
#### Table of Contents ####
####***********************

# 0: Preparation 
# 1: Load Packages for Analysis
# 2: Set Features
# 3: Load Functions 
# 4: Create Plotting Objects

####********************
#### 0: Preparation ####
####********************

# 0a Indicate that the script was run
# although it is intuitive to run this at the end of the script, 
# that creates a recursion with the functions
Ran_a_00_conusApp <- "Ran_a_00_conusApp"

# 0b Load pacman package
library(pacman)

####***********************************
#### 1: Load Packages for Analysis ####
####***********************************

# 1a Load Packages
p_load(tictoc, # keeping track of timing
       ape, 
       DHARMa, geoR, gstat) # Moran's I 

# ggsci provides the pallette we use to visualize the folds
#library(devtools)
#install_github('hunzikp/velox')
# nice way to make voronoi's
#if (!require(devtools)) install.packages("devtools")
#devtools::install_github("walshc/voronoi")

####*********************
#### 2: Set Features ####
####*********************

# 2a set the projection string 


####*************************
#### 3: Source Functions ####
####*************************

# 3a Get the names of all of the scripts that are just functions
# we want both the stable and unstable functions. 
myFunctions <- list.files(path = here::here('uncertainty_factor_analysis_ISEE',
                                                  'scripts', '0_functions'))

# 3b Define function to run sources 
source_myFunction <- function(FunctionName){
        source(here::here('uncertainty_factor_analysis_ISEE',
                          'scripts', '0_functions', FunctionName))
}

# 3c Source all the function scripts
# we don't actually need the assignment, it just removes annoying 
# output generated by the sourcing code. 
# since we are just sourcing these, we can just use map. 
a <- map(myFunctions, source_myFunction)
            
rm(a, source_myFunction, myFunctions)

####********************************
#### 4: Create Plotting Objects ####
####********************************

plotTheme <- theme_minimal()
