
%[W] = train_predict_BNE_sp('2013', 'avgscmjscc',0.5, 'all', 'noResid')
%[W] = train_predict_BNE_sp('2013', 'avgscmjscc',1.5, 'all', 'noResid')
%[W] = train_predict_BNE_sp('2010', 'avgscmjsccme',1.5, 'NYS', 'resid')
[W] = train_predict_BNE_sp('2010', 'avgscmjscc',1.5, 'all', 'resid')
%[W] = train_predict_BNE_sp('2012', 'avgscmjscc',1.5, 'NYS', 'resid')
%[W] = train_predict_BNE_sp('2013', 'avgscmjscc',1.5, 'NYS', 'resid')
%[W] = train_predict_BNE_sp('2014', 'avgscmjscc',1.5, 'NYS', 'resid')
%[W] = train_predict_BNE_sp('2015', 'avgscmjscc',1.5, 'NYS', 'resid')

%[W] = train_predict_BNE_sp('2010', 'avgscmjscc',0.1, 'all', 'resid')
%[W] = train_predict_BNE_sp('2011', 'avgscmjscc',0.1, 'all', 'resid')
%[W] = train_predict_BNE_sp('2012', 'avgscmjscc',0.1, 'all', 'resid')
%[W] = train_predict_BNE_sp('2013', 'avgscmjscc',0.1, 'all', 'resid')
%[W] = train_predict_BNE_sp('2014', 'avgscmjscc',0.1, 'all', 'resid')
%[W] = train_predict_BNE_sp('2015', 'avgscmjscc',0.1, 'all', 'resid')
%[W] = train_predict_BNE_spt('avgscmjscc',0.1, 01, 'all')
