# Task: Project Set Up 
# File: 0_00_config_env_uncert_analysis.R
# SubProject: Analysis of BNE PM2.5 Predictive Uncertainty
# Project: Bayesian Nonparametric Ensemble 
# Author: Sebastian T. Rowland <sr3463@cumc.columbia.edu>

#### ------------------- ####
####  Table of Contents  ####
#### ------------------- ####

# 0: Preparation 
# 1: Load Packages for Analysis
# 2: Set Features
# 3: Load Functions 
# 4: Create Plotting Objects

#### ---------------- ####
####  0: Preparation  ####
#### ---------------- ####

# 0.a. indicate that the script was run
# although it is intuitive to run this at the end of the script, 
# that creates a recursion with the functions
ran_a_00_uncert <- 'ran_a_00_uncert'

# 0.b. load pacman package
library(pacman)

# 0.c. project folder name 
dir.proj <- 'str_uncert_analysis'

merraVer <- 'meBlend'
# merraVer <- 'truncated MERRA'
# merraVer <- 'nome'

if (merraVer == 'meBlend') {
  outPath <- 'outputs' ; ppdPath <- 'annual'
} else if (merraVer == 'truncated MERRA') {
  outPath <- 'outputs_meTrunc'; ppdPath <- 'annual_meTrunc'
  } else if (merraVer == 'nome') {
  outPath <- 'outputs_nome'; ppdPath <- 'annual_nome'
  }

#### ------------------------------- ####
####  1: Load Packages for Analysis  ####
#### ------------------------------- ####

# 1.a. load packages
p_load(tictoc, # keeping track of timing
       DHARMa, gstat,  # Moran's I 
       mgcv, dlnm,
       tidycensus, prism) 

#### ----------------- ####
####  2: Set Features  ####
#### ----------------- ####

# 2a no subproject-specific features yet

#### --------------------- ####
####  3: Source Functions  ####
#### --------------------- ####

# 3.a. get the names of all of the scripts that are just functions
# we want both the stable and unstable functions. 
myFunctions <- list.files(path = here::here(dir.proj,
                                                  'code', '0_functions'))

# 3.b. define function to run sources 
source_myFunction <- function(FunctionName){
        source(here::here(dir.proj,
                          'code', '0_functions', FunctionName))
}

# 3.c. source all the function scripts
# we don't actually need the assignment, it just removes annoying 
# output generated by the sourcing code. 
# since we are just sourcing these, we can just use map. 
a <- map(myFunctions, source_myFunction)
       
# 3.d. clean environment - we don't need these objects anymore     
rm(a, source_myFunction, myFunctions)

#### ---------------------------- ####
####  4: Create Plotting Objects  ####
#### ---------------------------- ####

# 4.a. baseline plot theme is the minimal plot
plotTheme <- theme_minimal()
